/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.mybatis:mybatis:3.5.13")
    api("com.mybatis-flex:mybatis-flex-spring:1.5.3")
    api("com.mysql:mysql-connector-j:8.0.33")
    api("org.xerial:sqlite-jdbc:3.41.2.1")
    api("com.oracle.ojdbc:ojdbc8:19.3.0.0")
    api("com.zaxxer:HikariCP:4.0.3")
    api("com.google.code.gson:gson:2.10.1")
    api("com.alibaba:druid:1.2.18")
    api("com.jfinal:enjoy:5.1.1")
    api("org.projectlombok:lombok:1.18.26")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testImplementation("org.springframework:spring-web:6.0.11")
}
apply plugin: "com.vanniktech.maven.publish"

group = "io.github.vino42"
version = "1.0-SNAPSHOT"
description = "mybatis-flex-codegen"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
